### ISSUE TITLE
daphne could not be found within PATH or Pipfile's [scripts]:

### ISSUE THREAD

**Issue by Hiran2912** [e-m-b-a/embark#109]
**To Reproduce**
1. EMBArk installation (default mode/docker-mode)
2. Start EMBArk: sudo ./run-server.sh

OS: [Kali Linux 2023.01]

[ JOB] Starting migrations - log to embark/logs/migration.log
Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 14, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 26, in <module>
    main()
  File "/var/www/embark/./manage.py", line 17, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 14, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 26, in <module>
    main()
  File "/var/www/embark/./manage.py", line 17, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

[ JOB] Collecting static files
Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 14, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 26, in <module>
    main()
  File "/var/www/embark/./manage.py", line 17, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

[ JOB] Starting runapscheduler
Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 14, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 26, in <module>
    main()
  File "/var/www/embark/./manage.py", line 17, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

[ JOB] Starting Apache
Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 14, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/embark/./manage.py", line 26, in <module>
    main()
  File "/var/www/embark/./manage.py", line 17, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

[ JOB] Starting daphne(ASGI) - log to /embark/logs/daphne.log
Error: the command daphne could not be found within PATH or Pipfile's [scripts].

=============================================================

EMBA logs are under /var/www/emba_logs/<id> 

Server started on http://embark.local

**Comment by m-1-k-3** [comment]
Unsupported OS. Please check the prerequisites here: https://github.com/e-m-b-a/embark/wiki/Installation#prerequisites

**Comment by spon94** [comment]
hi，I encountered the same issue, but my operating system is consistent with the prerequisites mentioned.
