### ISSUE TITLE
CVE-search won't start 

### ISSUE THREAD

**Issue by Pompommy** [e-m-b-a/embark#170]
**Describe the bug**
On Embark server start (./run-server.sh -a hostname), CVE-search won't start, with following messages.

*************************************************

 cve-search - testing
[*] CVE-search not working - restarting Mongo database for CVE-search
[*] CVE-search not working - restarting Mongo database for CVE-search
    cve-search - not ok
[-] The needed CVE database is not responding as expected.
[-] CVE checks are currently not possible!

*************************************************

I tried suggestions by : https://github.com/e-m-b-a/emba/issues/187

$source ./external/emba_venv/bin/activate
$ ./external/cve-search/sbin/db_updater.py -f

*************************************************

following error messages were displayed

2023-11-26 13:33:23,040 - DBUpdater - INFO     - Dropping metadata
Traceback (most recent call last):
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/CveXplore/database/connection/mongo_db.py", line 41, in __init__
    collections = self._dbclient.list_collection_names()
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/database.py", line 1149, in list_collection_names
    return [result["name"] for result in self.list_collections(session=session, **kwargs)]
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/database.py", line 1101, in list_collections
    return self.__client._retryable_read(_cmd, read_pref, session)
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1525, in _retryable_read
    server = self._select_server(read_pref, session, address=address)
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1297, in _select_server
    server = topology.select_server(server_selector)
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/topology.py", line 312, in select_server
    server = self._select_server(selector, server_selection_timeout, address)
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/topology.py", line 296, in _select_server
    servers = self.select_servers(selector, server_selection_timeout, address)
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/topology.py", line 247, in select_servers
    server_descriptions = self._select_servers_loop(selector, server_timeout, address)
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/pymongo/topology.py", line 269, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 65634923970bf911dc40b3e1, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxuser/download/embark/emba/./external/cve-search/sbin/db_updater.py", line 121, in <module>
    cvex = CveXplore()
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/CveXplore/main.py", line 73, in __init__    self.datasource = MongoDBConnection(**mongodb_connection_details)
  File "/home/linuxuser/download/embark/emba/external/emba_venv/lib/python3.10/site-packages/CveXplore/database/connection/mongo_db.py", line 43, in __init__
    raise DatabaseConnectionException(
CveXplore.errors.database.DatabaseConnectionException: Connection to the database failed: 127.0.0.1:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 65634923970bf911dc40b3e1, topology_type: Unknown, servers: [<ServerDescription ('127.0.0.1', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('127.0.0.1:27017: [Errno 111] Connection refused')>]>

***********************************************

I've found a clue from above messages that "127.0.0.1:27017" is the the address of database instead of "172.36.0.1:27017"

I think this is the main reason why CVE-search won't start.

Can you fix the code to address this issue ?

**To Reproduce**
1. EMBArk installation (docker-mode)
2. Start EMBArk: sudo ./run-server.sh -a hostname
3. CVE-search won't start with database problem
4. use command: source ./external/emba_venv/bin/activate
5. use command: ./external/cve-search/sbin/db_updater.py -f
5. See error

 - OS: Ubuntu 22.04

**Comment by m-1-k-3** [comment]
Working on it here https://github.com/e-m-b-a/emba/pull/913
Please test and give feedback

**Comment by Pompommy** [comment]
I've tested the code (#913). instaler.sh -d stopped at IF50_aggregator_common. 
./installer.sh: line 354: IF20_nvd_feed: command not found

****************************************
sudo ./installer.sh -d

[+] IF50_aggregator_common
=================================================================
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
p7zip-full is already the newest version (16.02+dfsg-8).
The following packages were automatically installed and are no longer required:
  eatmydata libeatmydata1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
./installer.sh: line 354: IF20_nvd_feed: command not found
------------------------------------------------------------------------------------------------
Error detected - status code 127
Command:  echo -e "Command:  ${ORANGE}${BASH_COMMAND}${NC}"
Location:  ./installer.sh, line 354
Stack Trace:
    [1] main(): ./installer.sh, line 354 -> main -d

Important: Consider filling out a bug report at https://github.com/e-m-b-a/emba/issues

**Comment by m-1-k-3** [comment]
please check again

**Comment by Pompommy** [comment]
It's finished without any error this time. Thanks!
