### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by keesj-exset** [e-m-b-a/embark#40]
![Screenshot from 2022-04-19 13-37-26](https://user-images.githubusercontent.com/62298192/163995111-0ecb6a76-cd32-45c9-addb-5c1c500e5ab4.png)
**Describe the bug**

While uploading "large" files the upload UI is not very clear on why an upload is failing.
Doing some debugging in the web console I was able to see "Request Entity Too Large".
Pressing the upload button a few times also causes the progress bar to go.. weird

is there a setting to allow larger files? 
is there also a setting to allow to queue more analysis ?

**To Reproduce**
1. EMBArk installation (using EMBABox)
2. Start EMBArk: sudo ./run-server.sh
3. Use the firmware available here:430 MB file (ota update)
4. 
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Kali Linux 2022.01]

**Additional context**

Not sure but I also got this message (perhaps a race condition while uploading?)
```
2022-04-19 10:21:09,597 INFO     Listening on TCP address 0.0.0.0:8001                                    
Error notifying listener                             
Traceback (most recent call last):                   
  File "/home/vagrant/embark/.venv/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 836, in _dispatch_event
    cb(event)                                        
  File "/home/vagrant/embark/.venv/lib/python3.9/site-packages/django_apscheduler/jobstores.py", line 100, in handle_execution_event
    job_execution = DjangoJobExecution.atomic_update_or_create(                                           
  File "/home/vagrant/embark/.venv/lib/python3.9/site-packages/django_apscheduler/util.py", line 99, in func_wrapper
    result = func(*args, **kwargs)                   
  File "/home/vagrant/embark/.venv/lib/python3.9/site-packages/django_apscheduler/models.py", line 165, in atomic_update_or_create
    job_execution = DjangoJobExecution.objects.select_for_update().get(                                   
  File "/home/vagrant/embark/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 443, in get
    raise self.model.MultipleObjectsReturned(                                                             
django_apscheduler.models.DjangoJobExecution.MultipleObjectsReturned: get() returned more than one DjangoJobExecution -- it returned 2!

```

**Comment by keesj-exset** [comment]
It looks like the size can be increased in the startup script .

https://github.com/e-m-b-a/embark/blob/main/run-server.sh#L26

**Comment by m-1-k-3** [comment]
is it now working? I will include a note in the wiki

**Comment by keesj-exset** [comment]
Increasing the limit does appear to work (hence good to document how to increase the limit) but I will do more testing tomorrow. The UI issue remain. it appears it is possible to press the upload button multiple times causing multiple uploads (arguably this is a different issue) but still related to large files
