### ISSUE TITLE
Unable to connect to embark.local

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/embark#42]
**Describe the bug**
I start the run-server.sh and it drops these errors:

Loading .env environment variables...
Traceback (most recent call last):
  File "/home/seclab/embark/.venv/bin/daphne", line 8, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/home/seclab/embark/.venv/lib/python3.9/site-packages/daphne/cli.py", line 170, in entrypoint
    cls().run(sys.argv[1:])
  File "/home/seclab/embark/.venv/lib/python3.9/site-packages/daphne/cli.py", line 232, in run
    application = import_by_path(args.application)
  File "/home/seclab/embark/.venv/lib/python3.9/site-packages/daphne/utils.py", line 12, in import_by_path
    target = importlib.import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/seclab/embark/www/embark/./embark/asgi.py", line 20, in <module>
    asgi_application = get_asgi_application()
  File "/home/seclab/embark/.venv/lib/python3.9/site-packages/django/core/asgi.py", line 12, in get_asgi_application
    django.setup(set_prefix=False)
  File "/home/seclab/embark/.venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/seclab/embark/.venv/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/seclab/embark/.venv/lib/python3.9/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mod_wsgi'

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk: sudo ./run-server.sh
3. See error

**Expected behavior**
I can not get http://embark.local in the web browser.
Message is this:

"Unable to connect
Firefox can’t establish a connection to the server at embark.local."

**Desktop (please complete the following information):**
 - OS: [Kali Linux 2022.01]

**Additional context**
I reinstalled the EMBArk but got the same error. During the install I have these errors:

Installing dependencies from Pipfile.lock (df2d80)...
An error occurred while installing mod-wsgi-httpd==2.4.48.1 --hash=sha256:4ab310a26dcad14246a66b0440c61a2026fedb9e9face8f2989955881907e1f2! Will try again.
An error occurred while installing mod-wsgi-standalone==4.9.0 --hash=sha256:71a5bb625c8810325cd16b8c7ddab69041ba3a1f52f66e4d87aa8e76d582c255! Will try again.
An error occurred while installing mysqlclient==2.1.0 --hash=sha256:02c8826e6add9b20f4cb12dcf016485f7b1d6e30356a1204d05431867a1b3947 --hash=sha256:973235686f1b720536d417bf0a0d39b4ab3d5086b2b6ad5e6752393428c02b12 --hash=sha256:2c8410f54492a3d2488a6a53e2d85b7e016751a1e7d116e7aea9c763f59f5e8c --hash=sha256:e6279263d5a9feca3e0edbc2b2a52c057375bf301d47da2089c075ff76331d14 --hash=sha256:b62d23c11c516cedb887377c8807628c1c65d57593b57853186a6ee18b0c6a5b! Will try again.

**Comment by BenediktMKuehne** [comment]
`sudo apt install python3.*-dev`
should fix this problem

**Comment by BenediktMKuehne** [comment]
or just `python3.9-dev`

**Comment by torabi12** [comment]
Thank you I am not a linux expert, but python3.9-dev package install solved the problem. Last time it was working without manual installation maybe, I don't remember, but now it was required. Thanks again.
